### ISSUE TITLE
Sidecar rewrite: envoy

### ISSUE THREAD

**Issue by misohu** [canonical/envoy-operator#71]
### Context

We rewrite all of our charms using the sidecar with base charm pattern instead of the old podspec.

### What needs to get done

Rewrite the charm using sidecar with base charm pattern.

### Definition of Done

Charm is rewritten with sidecar with base charm pattern.
All of the tests are rewritten and passing.

**Comment by DnPlas** [comment]
When we work on this task, we have to have in mind that we will need to migrate the `k8s-service` relation interface from its SDI implementation to the newer one handled by a library. See https://github.com/canonical/mlops-libs/issues/2 for more information about the library and what it entails.

**Comment by ca-scribner** [comment]
This'll take a bit more effort than usual because of https://github.com/canonical/charmed-kubeflow-chisme/issues/89.  We need to solve https://github.com/canonical/charmed-kubeflow-chisme/issues/89 before we can write Envoy using the `CharmReconciler` because we need to push a config file to the container that requires inputs from other components.  

I have a working solution to this that wont be a huge effort, but it still adds maybe an extra half a day or so to the rewrite
